### ISSUE TITLE
missing gis folder

### ISSUE THREAD

**Issue by spark-brc** [spark-brc/QSWATMOD2-plugin#13]
**Describe the bug**
[from SWAT-MODFLOW community](https://groups.google.com/g/swat-modflow/c/-FV2-68vPQs/m/hCqjO47YAAAJ)

**To Reproduce**
1. Create a new project
2. load the HRU shapefile

**Expected behavior**

**Screenshots**
An error has occurred while executing Python code:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\GWHD\\Desktop\\QSWATMOD_NewDemo\\QSWATMOD_NewMBRW\\GIS\\org_shps\\hru_org.gpkg'
Traceback (most recent call last):
  File "C:\Users/GWHD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATMOD2\QSWATMOD2.py", line 1382, in hru_shapefile
    shutil.copy(f, outfile)
  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\GWHD\\Desktop\\QSWATMOD_NewDemo\\QSWATMOD_NewMBRW\\GIS\\org_shps\\hru_org.gpkg'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.22.11-Białowieża Białowieża, 106d33d7

Python Path:
C:/PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python
C:/Users/GWHD/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/GWHD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.11/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.11\bin\python39.zip
C:\PROGRA~1\QGIS32~1.11\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib
C:\Program Files\QGIS 3.22.11\bin
C:\PROGRA~1\QGIS32~1.11\apps\Python39
C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\site-packages\Pythonwin
C:/Users/GWHD/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Desktop (please complete the following information):**
 - QGIS version [e.g. 3.xx.x]
 - QSWATMOD Version [e.g. 2.6.1]

**Additional context**

**Comment by spark-brc** [comment]
The issue has been resolved.
